name: appli_tibu
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  http: ^0.13.6
  pedometer: ^4.1.1
  shared_preferences: ^2.5.3
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  intl: ^0.19.0 
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.png
    - assets/logo.png
    - assets/instagram.png